# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dba02f91de344bb9e4cc9d51df77240a3738add6c192d5d89978c2ea1fc77a3ea160e5b433960d4454209b1dd10f07ec6b5534ab81bfb7c27be47ac148a3edc

test:
  secret_key_base: ef7762cf678442915ffee6da4b61a8a79a7580e83573aeb000ccc9bcdc1ab2e59b31230976627f9010f1fd1b3bba75684b77605e1a1f21998cb66ee7f7125295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
